"use client";

import { FormEvent, useEffect, useState } from "react";
import { IoAdd, IoClose } from "react-icons/io5";
import HabitantePage,{EmptyState,ModuleHeader} from "@/components/HabitantePage";
import Pagination from "@/components/Pagination";
import {useAuth} from "@/features/authentication/AuthContext";
import {crearReporte,getReportes} from "@/services/reportes";
import type {CrearReporteRequest,Reporte} from "@/types/reportes";

const initial:Omit<CrearReporteRequest,'privada'>={titulo:'',descripcion:'',tipo:'mantenimiento',prioridad:'media',fecha_suceso:'',hora_suceso:''};
export default function ReportesHabitante(){const{token,user,activeMembership}=useAuth();const[items,setItems]=useState<Reporte[]>([]);const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[count,setCount]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[form,setForm]=useState(initial);
 const load=async()=>{if(!token||!user||!activeMembership)return;setLoading(true);try{const d=await getReportes(token,{privada:activeMembership.privada,creador:user.id,search:search||undefined,page});setItems(d.results);setCount(d.count);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar los reportes.')}finally{setLoading(false)}};
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void load()},[token,user,activeMembership,search,page]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!token||!activeMembership)return;try{await crearReporte(token,{...form,fecha_suceso:form.fecha_suceso||undefined,hora_suceso:form.hora_suceso||undefined,privada:activeMembership.privada});setOpen(false);setForm(initial);await load()}catch(err){setError(err instanceof Error?err.message:'No se pudo crear el reporte.')}};
 return <HabitantePage activeItem="Reportes"><ModuleHeader title="Mis reportes" subtitle="Informa incidencias y consulta su seguimiento." search={search} onSearch={v=>{setSearch(v);setPage(1)}} action={<button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-[#0a496a] px-6 py-4 font-bold text-white"><IoAdd/> Nuevo reporte</button>}/><EmptyState loading={loading} error={error} empty={!items.length}/>{!loading&&!error&&<div className="space-y-4">{items.map(r=><article key={r.id} className="rounded-2xl bg-white p-5 shadow"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold text-[#0a496a]">#{r.num} · {r.titulo}</h2><p className="mt-2 text-gray-600">{r.descripcion}</p><p className="mt-3 text-sm">Tipo: <b>{r.tipo||'General'}</b> · Prioridad: <b className="capitalize">{r.prioridad}</b></p></div><span className="h-fit rounded-lg bg-orange-100 px-3 py-2 font-semibold capitalize">{r.estado.replace('_',' ')}</span></div></article>)}</div>}<Pagination currentPage={page} totalPages={Math.max(1,Math.ceil(count/20))} onPageChange={setPage}/>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={submit} className="w-full max-w-2xl rounded-3xl bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-bold text-[#0a496a]">Nuevo reporte</h2><button type="button" onClick={()=>setOpen(false)}><IoClose size={28}/></button></div><div className="mt-5 grid gap-4"><input required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} placeholder="Título" className="rounded-xl border p-3"/><textarea required minLength={10} value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} placeholder="Describe lo sucedido" className="min-h-28 rounded-xl border p-3"/><div className="grid grid-cols-2 gap-4"><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} className="rounded-xl border p-3"><option value="mantenimiento">Mantenimiento</option><option value="seguridad">Seguridad</option><option value="convivencia">Convivencia</option><option value="otro">Otro</option></select><select value={form.prioridad} onChange={e=>setForm({...form,prioridad:e.target.value as CrearReporteRequest['prioridad']})} className="rounded-xl border p-3"><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option></select><input type="date" value={form.fecha_suceso} onChange={e=>setForm({...form,fecha_suceso:e.target.value})} className="rounded-xl border p-3"/><input type="time" value={form.hora_suceso} onChange={e=>setForm({...form,hora_suceso:e.target.value})} className="rounded-xl border p-3"/></div><button className="rounded-xl bg-[#0a496a] p-4 font-bold text-white">Enviar reporte</button></div></form></div>}</HabitantePage>}
